# Generated by Django 6.0.6 on 2026-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_match_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_match_score',
            field=models.IntegerField(default=0),
        ),
    ]
